version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
    # Имя базы данных
      - MYSQL_DATABASE=fullstack
    # Пароль для root
      - MYSQL_ROOT_PASSWORD=28J1.YT}-6{&-4Vyc[-bfMq=6#nT)s.r.-Mw19=YV]
    # Создать имя пользователя при желании
    #  - MYSQL_USER=yuri
    # Паролль ждя этого пользователя
    #  - MYSQL_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
